### PR TITLE
Add npm publish action on github release

### LINKED ISSUE #160: Setup NPM publishing from Github actions
## Feature Description
Add github action to automatically publish github releases to NPM registry.

## Is your feature request related to a problem?
At the moment syft.js can only be installed from github directly, which is slow because all bundling occurs on the user's machine

## What alternatives have you considered?
Publishing manually - might be error prone.

## Additional Context
Same thing should be done for threepio and syft-proto javascript libraries, so it's better to have solution that will fit all 3 libraries.

### PR DESCRIPTION
**Pull request by pedroespindula**
## Description
Add a github action to publish on NPM when a release is made.

(This PR is still a Draft because a NPM_TOKEN must be added to this project settings to work properly)

Fixes #160 

## Affected Dependencies
An NPM_TOKEN environment variable has to be set on the project settings. 

## How has this been tested?
This Github Action was run on a private repository for testing purposes.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by cereallarceny** [comment]
@pedroespindula hey, any updates on this?

**Comment by pedroespindula** [comment]
Hey @cereallarceny, if the NPM_SECRET environment variable have been set, this PR can be reviewed and merged (I do not have the permissions to see the environment variables from this project). Can you check this for me?

**Comment by cereallarceny** [comment]
@vvmnnnkv ?

**Comment by vvmnnnkv** [comment]
Looks good!
I wonder if we could do similar to PySyft release action that automatically uses tag (release) name for publishing.
Suggested action simply publishes master branch, i.e. version in package.json must be updated manually before creating release.

**Review by vvmnnnkv — APPROVED** [review]

**Comment by cereallarceny** [comment]
I’m actually going to close this as we are going to use the NP package to release new versions manually. We won’t be using Github Actions.

**Pull request closed without merging**
