### PR TITLE
Add singleton support for Logger class

### PR DESCRIPTION
**Pull request by tsingh2k15**
My attempt to contribute and help for https://github.com/OpenMined/syft.js/issues/63

- Modify Logger class such that a single instance can be reused across app.
- Update unit tests impacted by this change.
- Fix failing tests due to incorrect protobuf objects used in source code. {Ignore this, seems already fixed in master when I rebased)

Note: I did not freeze Logger instance because it is required to be
spied in jest unit tests. Freezing it would have not let it be spied by
jest mocks on log function. This change should allow reuse of a single
logger instance but improper use of logger inside source code can still
allow the verbose setting to be misused.

### CODE REVIEW

**Comment by cereallarceny** [comment]
@tsingh2k15 Does this preserve the `verbose` setting originally set in the main `Syft` class? You should be able to set `verbose: true` and get logs or `verbose: false` and not get them... all within the main `new syft()` call. Can you confirm this and I'll merge?

**Comment by tsingh2k15** [comment]
> @tsingh2k15 Does this preserve the `verbose` setting originally set in the main `Syft` class? You should be able to set `verbose: true` and get logs or `verbose: false` and not get them... all within the main `new syft()` call. Can you confirm this and I'll merge?

@cereallarceny Sure, I will look into it and get back to you.

**Comment by tsingh2k15** [comment]
> > @tsingh2k15 Does this preserve the `verbose` setting originally set in the main `Syft` class? You should be able to set `verbose: true` and get logs or `verbose: false` and not get them... all within the main `new syft()` call. Can you confirm this and I'll merge?
> 
> @cereallarceny Sure, I will look into it and get back to you.

@cereallarceny I added unit test to validate singleton behavior. It works as expected. Let me know your thoughts. https://github.com/OpenMined/syft.js/pull/106/commits/7925f0f0410c2fbd8dfb9f2c1e6948ab521afbcb

**Review by cereallarceny — APPROVED** [review]

**Comment by cereallarceny** [comment]
I'm good to merge this once @vvmnnnkv approves.

**Comment by tsingh2k15** [comment]
> I'm good to merge this once @vvmnnnkv approves.

@vvmnnnkv Can you please review ? There were some merge conflicts I have resolved, but please let me know if I may have missed something while resolving merge conflicts. Thanks!

**Comment by tsingh2k15** [comment]
> > I'm good to merge this once @vvmnnnkv approves.
> 
> @vvmnnnkv Can you please review ? There were some merge conflicts I have resolved, but please let me know if I may have missed something while resolving merge conflicts. Thanks!

@vvmnnnkv I am following up on this, please let me know if you have questions.

**Review by vvmnnnkv — APPROVED** [review]
Looks good, thanks! :)

**Pull request merged**
