### PR TITLE
Forcing all websocket connections to secure if not debug mode.

### PR DESCRIPTION
**Pull request by rav7kantsingh**
@cereallarceny 
@vvmnnnkv 
#77

### CODE REVIEW

**Comment by cereallarceny** [comment]
@IamRavikantSingh I think you took this PR too literally. `verbose` is the correct setting. I didn't want us to change the name to `debug`. The main issue here isn't between `verbose` and `debug`, the issue is forcing `ws` connections to convert to `wss` when not running the library locally.

**Review by cereallarceny — CHANGES_REQUESTED** [review]
See comments above.

**Review by cereallarceny — APPROVED** [review]

**Comment by cereallarceny** [comment]
@vvmnnnkv, can I get your thoughts?

**Comment by cereallarceny** [comment]
@IamRavikantSingh Can you update your PR to work with the new worker API that was finished by @vvmnnnkv this morning?

**Comment by rav7kantsingh** [comment]
What am I supposed to do to pass `codecov` checks? @vvmnnnkv @cereallarceny

**Comment by cereallarceny** [comment]
@IamRavikantSingh don't worry about codecov. Just make sure that your code works with the new worker API - it's very different than the previous version of syft.js.

**Review by cereallarceny — APPROVED** [review]

**Pull request merged**
