### PR TITLE
Configured babel for jest to work with ES6 correctly

### PR DESCRIPTION
**Pull request by ribhu97**
Added babel-jest dependency to handle babel for jest.

### CODE REVIEW

**Comment by iamtrask** [comment]
Note: a continuation from conversation in https://github.com/OpenMined/syft.js/pull/26

**Review by cereallarceny — COMMENTED** [review]
@ribhu97 - this is much better than the previous PR.  However, what's the point here?  Our Jest test suite works fine with existing ES6 code.  Is this PR necessary or addressing a specific issue that hasn't already been solved?

**Comment by cereallarceny** [comment]
@iamtrask See comment above.

**Comment by cereallarceny** [comment]
We're already doing this.

**Comment by ribhu97** [comment]
The trasformIgnorePatterns was supposed to handle ES6 code within node_modules. Since, the jest suite worked with existing ES6 code I thought this would help.

**Comment by cereallarceny** [comment]
We do not want to compile ES6 code within node_modules.  That's not good practice.  Compilation should be up to the module author.

**Pull request closed without merging**
